
ALTER TABLE payment ADD created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE payment ALTER COLUMN created_at SET NOT NULL;

ALTER TABLE payment
    ALTER COLUMN amount SET NOT NULL;


ALTER TABLE refund ADD created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE refund ALTER COLUMN created_at SET NOT NULL;
