spring:
  application:
    name: product-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8071
  datasource:
    url: jdbc:postgresql://localhost:5432/webstore?currentSchema=webstore
    username: user
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
