spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/otabek-samatov/webstore-config
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true
server:
  port: 8071
  


#Enable all Spring Boot Actuator endpoints.
management:
  endpoints:
    web:
      exposure:
        include: "*"