spring:
  application:
    name: config-server
  profiles:
    active:
    - native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/otabek-samatov/webstore-config.git
          default-label: master
server:
  port: 8071
  


#Enable all Spring Boot Actuator endpoints.
management:
  endpoints:
    web:
      exposure:
        include: "*"